import "./deploy/erc20Mock.deploy";
import "./deploy/pipeline.deploy";
import "./deploy/aaveV3Mock.deploy";
import "./deploy/yearnFactoryMock.deploy";
import "./deploy/factory.deploy";
import "./deploy/registry.deploy";
import "./addLiquidity";
import "./testSetup";
import "./fantomSetup";
